[package]
name = "three-d-opengl-example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = "0.25.0"
image = "0.24.7"
three-d = "0.16.3"
